version: '3.3'

services: 
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always 
    env_file:
      - ./config/db.env
    

  wordpress:
    depends_on: # Identifica container que devem rodar antes deste
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wordpress.env
      

volumes: 
  db_data: {}